api = "0.2"

[buildpack]
  id = "com.anynines.buildpacks.rvm-go"
  name = "RVM Buildpack in Go"
  version = "0.1.3"

[metadata]
  include_files = ["bin/build","bin/detect","buildpack.toml"]

  [metadata.configuration]
    uri = "https://get.rvm.io"
    default_rvm_version = "1.29.10"
    default_ruby_version = "2.7.1"
    default_bundler_version = "2.1.4"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "heroku-18"
